### ISSUE TITLE
Failed to delete snapshots with older_than parameter

### ISSUE THREAD

**Issue by monsterbnd** [open-e/jdss-api-tools#41]
Hi.
I testing HA Cluster.
Version:	1.0up27.32558
Release date:	2019-01-11
Serial number:	T0005556
Storage:	Unlimited
Version status:	Activated
Expiration date:	2019-12-19

I need delete all snapshots. 
>jdss-api-tools.exe delete_snapshots --pool Pool-1 --volume vol10 --older_than 0seconds --delay 1 --node 192.168.0.221

2019-11-13 17:18:10  Node 192.168.0.221 is running.
Traceback (most recent call last):
  File "jdss-api-tools.py", line 4738, in <module>
    main()
  File "jdss-api-tools.py", line 4677, in main
    command_processor()
  File "jdss-api-tools.py", line 4397, in command_processor
    delete_snapshots( vol_type )
  File "jdss-api-tools.py", line 2131, in delete_snapshots
    snapshots_names = get_all_volume_snapshots_older_than_given_age(vol_type)
  File "jdss-api-tools.py", line 2171, in get_all_volume_snapshots_older_than_given_age
    snapshots_names = [snapshot['name'] for snapshot in snapshots['entries'] if snapshot_creation_to_seconds(snapshot['creation']) > older_than]
KeyError: 'creation'
[8760] Failed to execute script jdss-api-tools

**Comment by januszbak** [comment]
This is fixed. Please download latest version. Thank you!

**Comment by januszbak** [comment]
Fixed
